
if(typeof(LoadLangFile)!="undefined" && LoadLangFile.isEn()){
tinyMCE.addI18n('en.ablesky',{
style_select:"Styles",
font_size:"Font size",
fontdefault:"Font family",
block:"Format",
paragraph:"Paragraph",
div:"Div",
address:"Address",
pre:"Preformatted",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code sample",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Bold (Ctrl+B)",
italic_desc:"Italic (Ctrl+I)",
underline_desc:"Underline (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"Align left",
justifycenter_desc:"Align center",
justifyright_desc:"Align right",
justifyfull_desc:"Align full",
bullist_desc:"Unordered list",
numlist_desc:"Ordered list",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"Undo (Ctrl+Z)",
redo_desc:"Redo (Ctrl+Y)",
link_desc:"Insert/edit link",
unlink_desc:"Unlink",
image_desc:"Insert/edit image",
cleanup_desc:"Cleanup messy code",
code_desc:"Edit HTML Source",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Insert horizontal ruler",
removeformat_desc:"Remove formatting",
custom1_desc:"Your custom description here",
forecolor_desc:"Select text color",
backcolor_desc:"Select background color",
charmap_desc:"Insert custom character",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"Cut",
copy_desc:"Copy",
paste_desc:"Paste",
image_props_desc:"Image properties",
newdocument_desc:"New document",
help_desc:"Help",
blockquote_desc:"Blockquote",
clipboard_msg:"Copy/Cut/Paste is not available in Mozilla and Firefox.\r\nDo you want more information about this issue?",
path:"Path",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"More colors"
});
} else {
tinyMCE.addI18n('en.ablesky',{
style_select:"样式",
font_size:"大小",
fontdefault:"字体",
block:"格式",
paragraph:"段落",
div:"Div",
address:"地址",
pre:"预先",
h1:"标题 1",
h2:"标题 2",
h3:"标题 3",
h4:"标题 4",
h5:"标题 5",
h6:"标题 6",
blockquote:"引用",
code:"代码",
samp:"代码示例",
dt:"长期的定义",
dd:"定义说明",
bold_desc:"粗体 (Ctrl+B)",
italic_desc:"斜体 (Ctrl+I)",
underline_desc:"下划线 (Ctrl+U)",
striketrough_desc:"删除线",
justifyleft_desc:"左对齐",
justifycenter_desc:"居中对齐",
justifyright_desc:"右对齐",
justifyfull_desc:"对齐",
bullist_desc:"无序列表",
numlist_desc:"有序列表",
outdent_desc:"减小缩进",
indent_desc:"缩进",
undo_desc:"撤消（按Ctrl+Z)",
redo_desc:"重做（按Ctrl + Y ）",
link_desc:"插入/修改链接",
unlink_desc:"断开",
image_desc:"插入/编辑图像",
cleanup_desc:"清理乱代码",
code_desc:"编辑HTML源代码",
sub_desc:"标",
sup_desc:"标",
hr_desc:"插入水平尺",
removeformat_desc:"移除格式",
custom1_desc:"您自订的描述在这里",
forecolor_desc:"选择文字颜色",
backcolor_desc:"选择背景颜色",
charmap_desc:"插入自定义字符",
visualaid_desc:"切换准则/无形要素",
anchor_desc:"插入/编辑锚",
cut_desc:"剪切",
copy_desc:"复制",
paste_desc:"粘贴",
image_props_desc:"图像性能",
newdocument_desc:"新文件",
help_desc:"帮助",
blockquote_desc:"引用",
clipboard_msg:"复制/剪切/粘贴并不适用于Mozilla和Firefox 。\r\n是否希望进一步了解这个问题?",
path:"路径",
newdocument:"你确定要清除文件所有的内容吗?",
toolbar_focus:"转到跳转工具 - Alt+Q, 转到编辑 - Alt-Z, 转到文件路径 - Alt-X",
more_colors:"更多颜色"
});

}